# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_update_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="is_public_share_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cv",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
