# Generated by Django 6.0.3 on 2026-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_share_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cv_photos/'),
        ),
    ]
