# Generated by Django 5.1 on 2026-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_add_photo_to_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
