# Generated by Django 6.0.3 on 2026-09-14 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_cv_is_unlocked_cv_unlocked_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_versions', to='cv.cv'),
        ),
        migrations.AddField(
            model_name='cv',
            name='tailor_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('generate', 'CV yaratish'), ('tailor', 'Vakansiyaga moslashtirish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='cv.cv')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
