# Generated by Django 6.0.3 on 2026-09-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cv_job_description_cv_parent_cv_tailor_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='selected_template',
            field=models.CharField(choices=[('ats_modern', 'ATS Zamonaviy'), ('ats', 'ATS Standart'), ('classic', 'Klassik'), ('modern', 'Zamonaviy'), ('creative', 'Kreativ'), ('executive', 'Executive'), ('minimal', 'Minimal'), ('dark', 'Dark Mode'), ('elegant', 'Elegant'), ('free_classic', 'Free Classic (legacy)'), ('premium_modern', 'Premium Modern (legacy)')], default='classic', max_length=50),
        ),
    ]
