# Generated by Django 6.0.3 on 2026-09-14 20:49

import uuid
from django.db import migrations, models


def fill_public_ids(apps, schema_editor):
    CV = apps.get_model("cv", "CV")
    for cv in CV.objects.filter(public_id__isnull=True).only("pk"):
        CV.objects.filter(pk=cv.pk).update(public_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_cv_selected_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiusage',
            options={'ordering': ('-created_at',), 'verbose_name': "AI so'rovi", 'verbose_name_plural': "AI so'rovlari"},
        ),
        migrations.AddField(
            model_name='aiusage',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Narx, $'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        # Mavjud CV larga har biriga alohida UUID berish uchun 3 bosqich
        migrations.AddField(
            model_name='cv',
            name='public_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(fill_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cv',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
