# Generated by Django 6.0.3 on 2026-09-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_aiusage_options_aiusage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'CV lar'},
        ),
    ]
