# Generated by Django 6.0.3 on 2026-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_cv_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Masalan: sotuvchi-konsultant', max_length=80, unique=True, verbose_name='URL')),
                ('profession', models.CharField(help_text='Masalan: Sotuvchi-konsultant', max_length=100, verbose_name='Kasb nomi')),
                ('category', models.CharField(blank=True, help_text="Masalan: Savdo, IT, Ta'lim", max_length=60, verbose_name="Yo'nalish")),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO sarlavha')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='SEO tavsif')),
                ('intro', models.TextField(blank=True, help_text="Bo'sh qator — yangi paragraf", verbose_name='Sahifa matni (maslahatlar)')),
                ('cv_json', models.JSONField(verbose_name="Rezyume ma'lumotlari")),
                ('template_code', models.CharField(default='ats_modern', max_length=50, verbose_name='Shablon')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rezyume namunasi',
                'verbose_name_plural': 'Rezyume namunalari',
                'ordering': ('sort_order', 'profession'),
            },
        ),
        migrations.CreateModel(
            name='TemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('is_pro', models.BooleanField(default=False, help_text='Pro shablonda PDF/Word faqat kredit yoki Pro bilan. Bepul shablonda 1 ta bepul PDF bor.', verbose_name='Pro shablon')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatish")),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Shablon sozlamasi',
                'verbose_name_plural': 'Shablon sozlamalari',
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='free_pdf',
            field=models.BooleanField(default=False, verbose_name='Bepul PDF ochilgan'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='selected_template',
            field=models.CharField(choices=[('ats_modern', 'ATS Zamonaviy'), ('ats', 'ATS Standart'), ('classic', 'Klassik'), ('modern', 'Zamonaviy'), ('creative', 'Kreativ'), ('executive', 'Executive'), ('minimal', 'Minimal'), ('dark', 'Dark Mode'), ('elegant', 'Elegant'), ('simple', 'Oddiy'), ('teal', 'Yashil panel'), ('bold', 'Yorqin'), ('free_classic', 'Free Classic (legacy)'), ('premium_modern', 'Premium Modern (legacy)')], default='classic', max_length=50),
        ),
    ]
