# Generated by Django 6.0.3 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_seed_templates_and_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='kind',
            field=models.CharField(choices=[('generate', 'CV yaratish'), ('tailor', 'Vakansiyaga moslashtirish'), ('improve', "AI bilan to'ldirish")], max_length=20),
        ),
    ]
