# Generated by Django 6.0.3 on 2026-09-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_aiusage_improve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name="Sovg'a yoqilgan")),
                ('audience', models.CharField(choices=[('all', 'Har bir foydalanuvchiga (bir martadan)'), ('new', "Faqat yangi ro'yxatdan o'tganlarga"), ('not_paid', "Hali hech narsa to'lamaganlarga")], default='all', max_length=20, verbose_name='Kimga')),
                ('new_user_days', models.PositiveIntegerField(default=3, verbose_name='«Yangi» necha kun hisoblanadi')),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='0 — cheksiz', verbose_name="Kuniga nechta sovg'a")),
                ('title', models.CharField(default='Siz bugungi baxtli foydalanuvchimizsiz!', max_length=120, verbose_name='Sarlavha')),
                ('text', models.TextField(default="Sizga sovg'a: shu rezyumeni <b>istalgan shablonda</b> — Pro shablonlarda ham — PDF qilib yuklab oling. Butunlay bepul.\nFaylning pastida saytimiz nomi qoladi — do'stlaringizga ko'rsatsangiz, ular ham shunday rezyume yasay oladi.", help_text='Yangi qator — yangi paragraf. <b>qalin</b> va <i>kursiv</i> ishlaydi.', verbose_name='Matn')),
                ('reactions', models.TextField(default='😊 Men ham xursandman\n🙏 Rahmat\n🙂 Menga kerak emas', help_text="Har qatorda bitta tugma. Kim nimani bosgani shu bo'limda ko'rinadi.", verbose_name='Javob tugmalari')),
                ('thanks_text', models.CharField(default='Rahmat! Fikringiz biz uchun muhim 💚', max_length=200, verbose_name='Javobdan keyingi matn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Baxtli foydalanuvchi sovg'asi",
                'verbose_name_plural': "Baxtli foydalanuvchi sovg'asi",
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='lucky_pdf',
            field=models.BooleanField(default=False, verbose_name="Sovg'a PDF ochilgan"),
        ),
        migrations.CreateModel(
            name='LuckyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=60, verbose_name='Javobi')),
                ('downloaded', models.BooleanField(default=False, verbose_name='Yuklab oldi')),
                ('template_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reacted_at', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_grants', to='cv.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Berilgan sovg'a",
                'verbose_name_plural': "Berilgan sovg'alar",
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user',), name='one_lucky_gift_per_user')],
            },
        ),
    ]
