# Generated by Django 6.0.3 on 2026-09-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_lucky_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckygift',
            name='button_label',
            field=models.CharField(default="Sovg'ani olish — PDF", max_length=60, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='luckygift',
            name='confetti',
            field=models.BooleanField(default=True, verbose_name='Salyut animatsiyasi'),
        ),
        migrations.AddField(
            model_name='luckygift',
            name='show_popup',
            field=models.BooleanField(default=True, help_text="Rezyume tayyor bo'lishi bilan bir marta ochiladi. O'chirilsa — faqat yon tomondagi kartada bo'ladi.", verbose_name="Ekran o'rtasida chiqsin"),
        ),
        migrations.AddField(
            model_name='luckygift',
            name='sound',
            field=models.BooleanField(default=True, help_text="Telefon ovozi o'chiq bo'lsa yoki brauzer ruxsat bermasa — jim ochiladi", verbose_name='Salyut ovozi'),
        ),
        migrations.AddField(
            model_name='luckygrant',
            name='shown',
            field=models.BooleanField(default=False, verbose_name="Tabrik ko'rsatilgan"),
        ),
    ]
