# Generated by Django 6.0.3 on 2026-09-14 20:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloklangan IP',
                'verbose_name_plural': 'Bloklangan IP lar',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Masalan: biz-haqimizda, aloqa', unique=True, verbose_name='URL (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('body', models.TextField(blank=True, help_text="Oddiy matn. Bo'sh qator — yangi paragraf.", verbose_name='Matn')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name="Footerda ko'rsatish")),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sahifa',
                'verbose_name_plural': 'Sahifalar',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='mycv.uz', max_length=100, verbose_name='Sayt nomi')),
                ('maintenance_message', models.CharField(blank=True, help_text="Bo'sh bo'lsa ko'rsatilmaydi", max_length=300, verbose_name="E'lon (sayt tepasida)")),
                ('card_number', models.CharField(default='8600 0000 0000 0000', max_length=30, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(default='ISM FAMILIYA', max_length=100, verbose_name='Karta egasi')),
                ('card_bank', models.CharField(blank=True, default='Uzcard', max_length=100, verbose_name='Bank / karta turi')),
                ('payment_instructions', models.TextField(blank=True, default="To'lovni amalga oshirgach, chek skrinshotini shu yerga yuboring. 5–30 daqiqa ichida tekshiramiz.", verbose_name="To'lov yo'riqnomasi (botda)")),
                ('payment_notice', models.CharField(blank=True, default="Click va Payme ulanmoqda — hozircha to'lov Telegram bot orqali qabul qilinadi.", max_length=300, verbose_name="Saytdagi to'lov izohi")),
                ('bot_username', models.CharField(blank=True, help_text="Bo'sh bo'lsa .env dagi TELEGRAM_BOT_USERNAME ishlatiladi", max_length=100, verbose_name='Bot username (@siz)')),
                ('admin_chat_ids', models.CharField(blank=True, help_text='Vergul bilan. Yangi chek va murojaatlar shu chatlarga yuboriladi.', max_length=300, verbose_name='Admin Telegram chat ID lari')),
                ('support_telegram', models.CharField(blank=True, max_length=100, verbose_name='Yordam uchun Telegram (@username)')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('working_hours', models.CharField(blank=True, default='Dush–Shan, 9:00–21:00', max_length=100, verbose_name='Ish vaqti')),
                ('free_cv_limit', models.PositiveIntegerField(default=2, verbose_name='Bepul CV yaratish soni')),
                ('free_tailor_limit', models.PositiveIntegerField(default=1, verbose_name='Bepul vakansiyaga moslashtirish soni')),
                ('tailor_per_unlocked_cv', models.PositiveIntegerField(default=5, verbose_name='Ochilgan har bir CV uchun moslashtirish')),
                ('ai_model', models.CharField(default='gpt-4.1-mini', max_length=100, verbose_name='OpenAI modeli')),
                ('ai_price_input_per_1m', models.DecimalField(decimal_places=4, default=Decimal('0.40'), max_digits=10, verbose_name='Kirish narxi, $ / 1M token')),
                ('ai_price_output_per_1m', models.DecimalField(decimal_places=4, default=Decimal('1.60'), max_digits=10, verbose_name='Chiqish narxi, $ / 1M token')),
                ('usd_to_uzs', models.PositiveIntegerField(default=12700, verbose_name="1 $ = so'm (hisobotlar uchun)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('logout', 'Chiqdi'), ('cv_create', 'CV yaratdi'), ('cv_tailor', 'Vakansiyaga moslashtirdi'), ('cv_unlock', 'CV ni kredit bilan ochdi'), ('cv_template', 'Shablon almashtirdi'), ('download_pdf', 'PDF yuklab oldi'), ('download_docx', 'Word yuklab oldi'), ('payment_request', "To'lov cheki yubordi"), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('contact', 'Murojaat yubordi'), ('blocked', 'Bloklandi'), ('unblocked', 'Blokdan chiqarildi'), ('limit_reached', 'Limitga yetdi')], db_index=True, max_length=30, verbose_name='Harakat')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faollik',
                'verbose_name_plural': 'Faollik jurnali',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism')),
                ('contact', models.CharField(max_length=150, verbose_name='Telefon / Telegram / email')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Javob berildi')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='ERROR', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Manba (logger)')),
                ('path', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Hal qilindi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xatolik',
                'verbose_name_plural': 'Xatoliklar',
                'ordering': ('-created_at',),
            },
        ),
    ]
