# Generated by Django 6.0.3 on 2026-09-15 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_staff_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('human', 'Real odam'), ('bot', 'Bot'), ('scanner', 'Skaner'), ('unknown', 'Aniqlanmagan')], db_index=True, default='unknown', max_length=10, verbose_name='Turi')),
                ('bot_name', models.CharField(blank=True, max_length=60, verbose_name='Bot nomi')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('ua_hash', models.CharField(blank=True, db_index=True, max_length=16)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('device', models.CharField(blank=True, max_length=10, verbose_name='Qurilma')),
                ('browser', models.CharField(blank=True, max_length=30)),
                ('os', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Manba')),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('landing_path', models.CharField(blank=True, max_length=300, verbose_name='Kirgan sahifa')),
                ('last_path', models.CharField(blank=True, max_length=300, verbose_name='Oxirgi sahifa')),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('in_telegram', models.BooleanField(default=False, verbose_name='Telegram Mini App')),
                ('did_builder', models.BooleanField(default=False, verbose_name='Yaratishni ochdi')),
                ('did_generate', models.BooleanField(default=False, verbose_name='Rezyume yaratdi')),
                ('did_login', models.BooleanField(default=False, verbose_name='Kirdi')),
                ('did_unlock', models.BooleanField(default=False, verbose_name="Ochdi (to'lov)")),
                ('did_download', models.BooleanField(default=False, verbose_name='Yukladi')),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tashrifchi',
                'verbose_name_plural': 'Tashrifchilar',
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('status', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.visitor')),
            ],
            options={
                'verbose_name': "Sahifa ko'rish",
                'verbose_name_plural': "Sahifa ko'rishlar",
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['first_seen', 'kind'], name='core_visito_first_s_4348a4_idx'),
        ),
    ]
