# Generated by Django 6.0.3 on 2026-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Masalan: /  yoki  /qollanma/  yoki  /namunalar/sotuvchi/', max_length=300, unique=True, verbose_name='Manzil')),
                ('title', models.CharField(blank=True, help_text="Google'da ko'k yozuv, ~60 belgigacha", max_length=70, verbose_name='Sarlavha (title)')),
                ('description', models.CharField(blank=True, help_text="Google'dagi kulrang matn, ~155 belgigacha", max_length=170, verbose_name='Tavsif (description)')),
                ('noindex', models.BooleanField(default=False, verbose_name="Google'da ko'rsatmaslik")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO sahifa',
                'verbose_name_plural': 'SEO sahifalar',
                'ordering': ('path',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_pdf_downloads',
            field=models.PositiveIntegerField(default=1, help_text='Yangi foydalanuvchi shuncha rezyumeni bepul shablonda PDF qilib oladi. Word — faqat paket yoki Pro.', verbose_name='Bepul PDF soni (har bir foydalanuvchiga)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_pdf_watermark',
            field=models.BooleanField(default=True, help_text='«tezrezyume.uz orqali yaratildi» — bepul reklama', verbose_name='Bepul PDF pastida sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Masalan: G-XXXXXXX', max_length=30, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Faqat content="..." ichidagi qiymat', max_length=120, verbose_name='Google Search Console kodi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_daily_limit',
            field=models.PositiveIntegerField(default=10, help_text="Soxta akkauntlar bilan suiiste'mol qilinmasligi uchun", verbose_name='Bir kishiga kuniga maksimal taklif bonusi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_enabled',
            field=models.BooleanField(default=True, verbose_name="Do'st taklif qilish yoqilgan"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_invitee_credits',
            field=models.PositiveIntegerField(default=0, verbose_name='Taklif bilan kelganga kredit'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_inviter_credits',
            field=models.PositiveIntegerField(default=1, verbose_name='Taklif qilganga kredit'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_description',
            field=models.CharField(blank=True, default="O'zingiz haqingizda oddiy yozing — AI 1 daqiqada professional rezyume tayyorlaydi. Tayyor namunalar, 12 ta shablon, PDF va Word. O'zbek, rus, ingliz tillarida.", max_length=170, verbose_name='Standart tavsif (description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_title',
            field=models.CharField(blank=True, default='Rezyume yaratish onlayn — bepul, 1 daqiqada | tezrezyume.uz', max_length=70, verbose_name='Standart sarlavha (title)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, help_text='Faqat raqam', max_length=20, verbose_name='Yandex Metrika ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, max_length=120, verbose_name='Yandex Webmaster kodi'),
        ),
    ]
