# Generated by Django 6.0.3 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_improve_limit',
            field=models.PositiveIntegerField(default=1, help_text="Tahrirlash sahifasida (masalan, namunadan boshlaganda) AI rezyumeni to'ldirib, yaxshilab beradi", verbose_name="Bepul «AI bilan to'ldirish» soni"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='improve_per_unlocked_cv',
            field=models.PositiveIntegerField(default=3, verbose_name="Ochilgan har bir CV uchun «AI bilan to'ldirish»"),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('logout', 'Chiqdi'), ('cv_create', 'CV yaratdi'), ('cv_tailor', 'Vakansiyaga moslashtirdi'), ('cv_edit', 'Rezyumeni tahrirladi'), ('cv_improve', "AI bilan to'ldirdi"), ('cv_unlock', 'CV ni kredit bilan ochdi'), ('cv_template', 'Shablon almashtirdi'), ('download_pdf', 'PDF yuklab oldi'), ('download_docx', 'Word yuklab oldi'), ('payment_request', "To'lov cheki yubordi"), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('contact', 'Murojaat yubordi'), ('blocked', 'Bloklandi'), ('unblocked', 'Blokdan chiqarildi'), ('credits_changed', "Kreditlari o'zgartirildi"), ('pro_granted', 'Pro berildi'), ('staff_granted', 'Panelga ruxsat berildi'), ('staff_removed', 'Panel ruxsati olindi'), ('limit_reached', 'Limitga yetdi'), ('referral', "Do'st taklif qildi"), ('promo_bonus', 'Aksiya bonusi oldi')], db_index=True, max_length=30, verbose_name='Harakat'),
        ),
    ]
