# Generated by Django 6.0.3 on 2026-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_broadcast_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification_file',
            field=models.CharField(blank=True, help_text="Masalan: google1a2b3c4d5e6f7g8h.html — Google bergan fayl nomi yoki uning ichidagi matn. Sayt shu manzilda Google kutgan javobni o'zi qaytaradi, faylni serverga yuklash shart emas.", max_length=120, verbose_name='Google HTML fayl nomi (HTML file)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='content="..." ichidagi qiymat. Butun <meta ...> tegini qo\'ysangiz ham bo\'ladi.', max_length=120, verbose_name='Google Search Console kodi (HTML tag)'),
        ),
    ]
