# Generated by Django 6.0.3 on 2026-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_google_verification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Kirdi'), ('logout', 'Chiqdi'), ('cv_create', 'CV yaratdi'), ('cv_tailor', 'Vakansiyaga moslashtirdi'), ('cv_edit', 'Rezyumeni tahrirladi'), ('cv_improve', "AI bilan to'ldirdi"), ('cv_unlock', 'CV ni kredit bilan ochdi'), ('cv_template', 'Shablon almashtirdi'), ('download_pdf', 'PDF yuklab oldi'), ('download_docx', 'Word yuklab oldi'), ('payment_request', "To'lov cheki yubordi"), ('payment_approved', "To'lov tasdiqlandi"), ('payment_rejected', "To'lov rad etildi"), ('contact', 'Murojaat yubordi'), ('blocked', 'Bloklandi'), ('unblocked', 'Blokdan chiqarildi'), ('credits_changed', "Kreditlari o'zgartirildi"), ('pro_granted', 'Pro berildi'), ('staff_granted', 'Panelga ruxsat berildi'), ('staff_removed', 'Panel ruxsati olindi'), ('limit_reached', 'Limitga yetdi'), ('referral', "Do'st taklif qildi"), ('promo_bonus', 'Aksiya bonusi oldi'), ('broadcast_bonus', 'Bot xabari bilan kredit oldi'), ('lucky_gift', "Baxtli foydalanuvchi sovg'asini oldi")], db_index=True, max_length=30, verbose_name='Harakat'),
        ),
    ]
