# Generated by Django 5.1 on 2026-09-14 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('used', 'Ishlatildi')], default='pending', max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.pricingplan'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='includes_docx_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='scope',
            field=models.CharField(choices=[('cv', 'Bitta CV (bir martalik)'), ('account', 'Akkaunt (obuna)')], default='account', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('cv_unlock', 'CV Unlock'), ('premium_template', 'Premium Template'), ('pdf_export', 'PDF Export')], default='subscription', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
