# Generated by Django 6.0.3 on 2026-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_pricing_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='max_cvs',
            field=models.PositiveIntegerField(default=0, help_text='Pro: davr ichida yangi CV yaratish soni'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='max_tailorings',
            field=models.PositiveIntegerField(default=0, help_text='Vakansiyaga moslashtirish soni'),
        ),
    ]
