# Generated by Django 6.0.3 on 2026-09-14 20:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_plan_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ('sort_order', 'price', 'id'), 'verbose_name': 'Tarif / paket', 'verbose_name_plural': 'Tariflar va paketlar'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='Kredit paketi uchun: nechta CV ochiladi', verbose_name='Kreditlar soni'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etiladi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bloklash sababi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.PositiveIntegerField(default=0, help_text='1 kredit = 1 CV ni ochish', verbose_name='Kreditlar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Oxirgi IP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='scope',
            field=models.CharField(choices=[('credits', 'Kredit paketi'), ('account', 'Pro obuna')], default='credits', max_length=20, verbose_name='Turi'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('status', models.CharField(choices=[('awaiting_receipt', 'Chek kutilmoqda'), ('pending', 'Tekshirilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='awaiting_receipt', max_length=20, verbose_name='Holat')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Chek')),
                ('receipt_caption', models.CharField(blank=True, max_length=500, verbose_name='Chek izohi')),
                ('admin_note', models.CharField(blank=True, help_text='Rad etsangiz foydalanuvchiga botda shu matn yuboriladi', max_length=500, verbose_name='Rad etish sababi / izoh')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_at', models.DateTimeField(blank=True, null=True, verbose_name='Chek yuborilgan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='users.pricingplan', verbose_name='Paket')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov (bot orqali)",
                'verbose_name_plural': "To'lovlar (bot orqali)",
                'ordering': ('-created_at',),
            },
        ),
    ]
