# Generated by Django 6.0.3 on 2026-09-14 21:06

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_credit_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='receipt',
            field=models.FileField(blank=True, upload_to=apps.users.models.receipt_upload_path, verbose_name='Chek'),
        ),
    ]
