# Generated by Django 6.0.3 on 2026-09-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rezyume_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Bitiruvchilar haftaligi', max_length=120, verbose_name='Nomi')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanishi')),
                ('ends_at', models.DateTimeField(verbose_name='Tugashi')),
                ('audience', models.CharField(choices=[('new', "Shu sanalarda ro'yxatdan o'tganlar"), ('all', 'Shu sanalarda kirgan barcha foydalanuvchilar')], default='new', max_length=10, verbose_name='Kimga')),
                ('bonus_credits', models.PositiveIntegerField(default=1, help_text='1 kredit = 1 rezyume PDF + Word, barcha shablonlar', verbose_name='Bonus kredit')),
                ('banner_text', models.CharField(blank=True, help_text="Masalan: 🎁 20-sentabrgacha ro'yxatdan o'tganlarga 2 ta rezyume tekin!", max_length=200, verbose_name="Saytdagi e'lon matni")),
                ('show_banner', models.BooleanField(default=True, verbose_name="E'lonni sayt tepasida ko'rsatish")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_pdf_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan bepul PDF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Taklif kodi'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_credits', models.PositiveIntegerField(default=0)),
                ('invitee_credits', models.PositiveIntegerField(default=0)),
                ('via', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromoGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='users.promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('promo', 'user'), name='one_grant_per_promo_user')],
            },
        ),
    ]
