# Generated by Django 6.0.3 on 2026-09-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_aiusage_improve'),
        ('users', '0012_pendingreferral_promo_userprofile_free_pdf_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nomi (faqat panel uchun)')),
                ('audience', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('cv_not_downloaded', 'Rezyume yaratgan, lekin yuklab olmaganlar'), ('no_cv', 'Hali rezyume yaratmaganlar'), ('selected', 'Tanlangan foydalanuvchilar')], default='all', max_length=30, verbose_name='Kimga')),
                ('selected_users', models.TextField(blank=True, help_text="Har qatorda bittadan: telefon, @username yoki panel ID si. Vergul bilan ham bo'ladi.", verbose_name='Tanlangan foydalanuvchilar')),
                ('text', models.TextField(help_text='{ism} — foydalanuvchi ismi, {kredit} — bonus kredit soni. <b>qalin</b>, <i>kursiv</i>, <a href="...">havola</a> ishlaydi.', verbose_name='Xabar matni')),
                ('attach_cv', models.BooleanField(default=False, help_text="Oxirgi rezyumesi «sovg'a» sifatida fayl bo'lib boradi. Rezyumesi yo'qlarga yuborilmaydi. Matn 1000 belgigacha.", verbose_name="Foydalanuvchining o'z rezyumesini PDF qilib yuborish")),
                ('bonus_credits', models.PositiveIntegerField(default=0, help_text="Xabar yetib borsa, hisobiga qo'shiladi", verbose_name='Bonus kredit')),
                ('feedback_options', models.TextField(blank=True, help_text="Har qatorda bitta tugma, masalan: «👍 Foydali bo'ldi». Kim nimani bosgani shu yerda ko'rinadi.", verbose_name='Javob tugmalari')),
                ('button_site', models.BooleanField(default=True, verbose_name='«Saytni ochish» tugmasi')),
                ('button_share', models.BooleanField(default=False, help_text='Foydalanuvchining shaxsiy taklif havolasi bilan', verbose_name="«Do'stga ulashish» tugmasi")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sending', 'Yuborilmoqda'), ('done', 'Yuborildi'), ('cancelled', "To'xtatildi")], db_index=True, default='draft', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot xabari',
                'verbose_name_plural': 'Bot xabarlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yetkazildi'), ('blocked', 'Botni bloklagan'), ('failed', 'Xato')], db_index=True, default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('response', models.CharField(blank=True, max_length=60, verbose_name='Javobi')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='users.broadcast')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cv.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'user'), name='one_message_per_broadcast_user')],
            },
        ),
    ]
