# Generated by Django 6.0.3 on 2026-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_broadcast_broadcastrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='selected_cvs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tanlangan rezyumelar'),
        ),
    ]
